package cn.uc.yiqibang.dao;

import cn.uc.yiqibang.beans.Cities;

public interface CitiesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int insert(Cities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int insertSelective(Cities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    Cities selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(Cities record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cities
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int updateByPrimaryKey(Cities record);
}