package cn.uc.yiqibang.dao;

import cn.uc.yiqibang.beans.TAdmin;

public interface TAdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int insert(TAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int insertSelective(TAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    TAdmin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TAdmin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int updateByPrimaryKey(TAdmin record);
}