package cn.uc.yiqibang.dao;

import cn.uc.yiqibang.beans.TComment;
import cn.uc.yiqibang.utils.Result;

public interface TCommentMapper {
	
	Result deleteByCondition(TComment comm);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int insert(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int insertSelective(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    TComment selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TComment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_comment
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int updateByPrimaryKey(TComment record);
}