package cn.uc.yiqibang.dao;

import javax.servlet.http.HttpServletRequest;

import cn.uc.yiqibang.beans.TNews;
import cn.uc.yiqibang.utils.Result;

public interface TNewsMapper {
	
	/**
	 * 获取所有新闻
	 * @return
	 */
	Result selectAll();
    /**
     * 删除新闻
     */
    Result deleteByPrimaryKey(Integer id);

    /**
     * 插入新闻图片
     */
    Result insertNewsPic(HttpServletRequest request);
    
    Result selectByLike(String likeStr);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int insert(TNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    Result insertSelective(TNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    TNews selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int updateByPrimaryKeySelective(TNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int updateByPrimaryKeyWithBLOBs(TNews record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_news
     *
     * @mbggenerated Fri Nov 10 16:12:02 GMT+08:00 2017
     */
    int updateByPrimaryKey(TNews record);
    
    Result insertNewsPic(HttpServletRequest request);
}